[package]
name = "scholar"
version = "0.1.0"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]

[dependencies]
clap = "~2.27.1"
error-chain = "0.11.0"
lazy_static = "0.2.9"
regex = "0.2.2"
reqwest = "0.8.1"
select = "0.4.2"

[[bin]]
name = "scholar"
doc = false
